-- Create recipes table
CREATE TABLE recipes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR NOT NULL,
    description VARCHAR,
    image VARCHAR,
    "ingredientAmounts" TEXT[] NOT NULL DEFAULT '{}',
    categories TEXT[] NOT NULL DEFAULT '{}',
    instructions TEXT[] NOT NULL DEFAULT '{}',
    created_by UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create RLS policies
ALTER TABLE recipes ENABLE ROW LEVEL SECURITY;

-- Allow everyone to read recipes
CREATE POLICY "Allow public to read recipes"
ON recipes FOR SELECT
USING (true);

-- Allow authenticated users to create recipes
CREATE POLICY "Allow authenticated to create recipes"
ON recipes FOR INSERT
WITH CHECK (auth.role() = 'authenticated');

-- Allow users to update their own recipes
CREATE POLICY "Allow users to update own recipes"
ON recipes FOR UPDATE
USING (auth.uid() = created_by);

-- Allow users to delete their own recipes
CREATE POLICY "Allow users to delete own recipes"
ON recipes FOR DELETE
USING (auth.uid() = created_by);

-- Create index for better performance
CREATE INDEX recipes_created_by_idx ON recipes(created_by);
CREATE INDEX recipes_categories_idx ON recipes(categories);
